server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379
      password: pt123
      lettuce:
        read-from: REPLICA_PREFERRED

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hmdp.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
